In [1]:
import pandas as pd

In [2]:
s = pd.Series([32,54,24,86,95,44,78])
print(s)

0    32
1    54
2    24
3    86
4    95
5    44
6    78
dtype: int64

In [3]:
s1 = pd.Series([54,24,86,95,44,78],index=["aditya","ananya","mayank","harhsita","shreya","aaranya"])
s1

aditya      54
ananya      24
mayank      86
harhsita    95
shreya      44
aaranya     78
dtype: int64

In [4]:
data = {
    "name" : ["Aditya","Ananya","Asmit"],
    "age" : [20,20,19],
    "college" : ["bvpcoep","bvpcoep","bmcc"]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

     name  age  college
0  Aditya   20  bvpcoep
1  Ananya   20  bvpcoep
2   Asmit   19     bmcc

In [7]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
df.columns

Index(['name', 'age', 'college'], dtype='object')

In [9]:
data = [["aditya",85],["ananya",80]]

In [10]:
df = pd.DataFrame(data,columns=["Name","12th Marks"])

In [11]:
df

     Name  12th Marks
0  aditya          85
1  ananya          80

In [12]:
data = {"stu1": ["aditya",85],"stu2": ["ananya",80]}
df=pd.DataFrame(data)
df

     stu1    stu2
0  aditya  ananya
1      85      80

In [13]:
import numpy as np

In [14]:
#using numpy array to create Data for DataFrame
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr,columns = ["a","b","c"])
df

   a  b  c
0  1  2  3
1  4  5  6

In [15]:
#read data from spreadsheet file
df = pd.read_excel("data.xlsx")

In [16]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
#read data from CSV 
df = pd.read_csv("data.csv")
df

      Name     School  Marks
0   Aditya        AFS     98
1   Ananya        DAV     86
2   Mayank  St Patrik     67
3  Anushka        AFS     56
4  Aaranya        KVS     76
5    Rahul        KVS     78

In [18]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [19]:
#EDA
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [22]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [23]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [24]:
df.shape

(244, 7)

In [25]:
import pandas as pd

In [26]:
#data selection and filtering using pandas
df = pd.read_excel("data.xlsx")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [27]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [28]:
df['Actor'][3]

'Ranbir Kapoor'

In [29]:
df[['Actor','Film']]

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1          Salman Khan           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan         Bhool Bhulaiyaa 2
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [30]:
df.loc[4]

Actor                   Ranveer Singh
Film                        Padmaavat
Year                             2018
Genre                      Historical
BoxOffice(INR Crore)              585
IMDb                              7.0
Name: 4, dtype: object

In [31]:
df.loc[4,"Film"]

'Padmaavat'

In [32]:
df.loc[3:5,["Actor","Film"]]

                Actor        Film
3       Ranbir Kapoor  Brahmastra
4       Ranveer Singh   Padmaavat
5  Ayushmann Khurrana   Andhadhun

In [33]:
df.iloc[0:3,2:4]

   Year      Genre
0  2023     Action
1  2017     Action
2  2016  Biography

In [34]:
df.at[4,"Actor"]  #more optimised method fot selecting single element

'Ranveer Singh'

In [35]:
df.iat[0,1]

'Pathaan'

In [36]:
df[df["IMDb"]>7]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [37]:
df[df["IMDb"]>7]["Actor"]

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: object

In [38]:
df[(df['IMDb']>7) & (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [39]:
df[(df['IMDb']>7) | (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [40]:
df.query("Year > 2018 and IMDb > 7")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [41]:
import pandas as pd
#data cleaning and preprocessing

In [42]:
df = pd.read_csv("data_sample.csv")

In [43]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [44]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [45]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [46]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [47]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [48]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [49]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [50]:
 df.fillna(method = "ffill")

/var/folders/3n/l65fddk923zd_p9fhnzdgmgw0000gn/T/ipykernel_13918/2260195037.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [51]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [52]:
df["City"].str.contains("delhi",case = False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [53]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [54]:
df["Email"].str.split("@")[5]

['eve', 'domain.com']

In [55]:
type(df["Email"].str.split("@")[3])

list

In [56]:
df2 = df.dropna().copy()

In [57]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [58]:
df2["Age"].astype(int)

0    25
2    30
4    22
6    25
7    25
Name: Age, dtype: int64

In [59]:
df["age group"] = df["Age"].apply(lambda x : "Adult" if x>=25 else "Minor")
df

      Name   Age         City Gender              Email   Join Date age group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [60]:
gender_map = {"F":"Female","M":"Male"}
df["Gender"] = df["Gender"].map(gender_map)
df

      Name   Age         City  Gender              Email   Join Date age group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Adult
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor

In [61]:
df["City"] = df["City"].replace({"Mumbai":"Bombay","Delhi":"New Delhi"})
df

      Name   Age         City  Gender              Email   Join Date age group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   NaN    New Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   NaN    New Delhi    Male    charlie@example  20-07-2021     Minor
4    David  22.0       Bombay    Male  david@example.com  12-11-2019     Minor
5      NaN  28.0    New Delhi  Female     eve@domain.com         NaN     Adult
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   NaN    New Delhi    Male    charlie@example  20-07-2021     Minor

In [62]:
#data transformation
df = pd.read_excel("data.xlsx")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [63]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [64]:
df.sort_values("Year",ascending = False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [65]:
df2 = df.sort_values(["Year","BoxOffice(INR Crore)"]).copy()

In [66]:
df2.reset_index()  #does not change index , just for showing

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,7,Hrithik Roshan,War,2019,Action,475,6.5
9,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [67]:
df2.reset_index(drop=True,inplace = True) #drop removes the old index(label) and inplace updates the df
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [68]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [69]:
df2 = df2[["Film","Actor","Genre","IMDb","Year","BoxOffice(INR Crore)"]]

In [70]:
df2

,Film,Actor,Genre,IMDb,Year,BoxOffice(INR Crore)
0,Dangal,Aamir Khan,Biography,8.4,2016,2024
1,Badrinath Ki Dulhania,Varun Dhawan,Romantic Comedy,6.1,2017,201
2,Tiger Zinda Hai,Salman Khan,Action,6.0,2017,565
3,Andhadhun,Ayushmann Khurrana,Thriller,8.3,2018,111
4,Stree,Rajkummar Rao,Horror Comedy,7.5,2018,180
5,Padmaavat,Ranveer Singh,Historical,7.0,2018,585
6,Good Newwz,Akshay Kumar,Comedy,7.0,2019,318
7,Uri: The Surgical Strike,Vicky Kaushal,Action,8.2,2019,342
8,War,Hrithik Roshan,Action,6.5,2019,475
9,Bhool Bhulaiyaa 2,Kartik Aaryan,Horror Comedy,5.9,2022,266
10,Brahmastra,Ranbir Kapoor,Fantasy,5.6,2022,431
11,Pathaan,Shah Rukh Khan,Action,7.2,2023,1050

In [71]:
#melt and pivot
import pandas as pd

In [72]:
data = {
    'Name' : ["Aditya","Rahul","Mayank","Aranya"],
    'Math': [85, 78, 92,34],
    'Science': [90, 82, 89,65],
    'English': [88, 85, 94,76]
}

In [73]:
df = pd.DataFrame(data)

In [74]:
print(df)

     Name  Math  Science  English
0  Aditya    85       90       88
1   Rahul    78       82       85
2  Mayank    92       89       94
3  Aranya    34       65       76

In [75]:
df2 = df.melt(id_vars = ["Name"],value_vars = ['Math','Science','English'],var_name = 'Subject',value_name='Score').copy()

In [76]:
df2

      Name  Subject  Score
0   Aditya     Math     85
1    Rahul     Math     78
2   Mayank     Math     92
3   Aranya     Math     34
4   Aditya  Science     90
5    Rahul  Science     82
6   Mayank  Science     89
7   Aranya  Science     65
8   Aditya  English     88
9    Rahul  English     85
10  Mayank  English     94
11  Aranya  English     76

In [77]:
df

     Name  Math  Science  English
0  Aditya    85       90       88
1   Rahul    78       82       85
2  Mayank    92       89       94
3  Aranya    34       65       76

In [78]:
df2.pivot_table(index = 'Name',columns = 'Subject', values = 'Score')

Subject  English  Math  Science
Name
Aditya      88.0  85.0     90.0
Aranya      76.0  34.0     65.0
Mayank      94.0  92.0     89.0
Rahul       85.0  78.0     82.0

In [87]:
#aggregation and grouping 
import pandas as pd

In [90]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})  
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [92]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [93]:
df.groupby("Department")["Salary"].sum()

Department
HR           175
IT           163
Marketing    180
Sales        155
Name: Salary, dtype: int64

In [94]:
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [95]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [96]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [103]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

            mean  max  min
Department
HR          87.5   90   85
IT          81.5   85   78
Marketing   90.0   92   88
Sales       77.5   80   75

In [106]:
df["deptAvg"] = df.groupby("Department")["Salary"].transform("mean")

In [105]:
df

  Department Team Gender  Salary  Age   JoinDate  deptAvg
0         HR    A      M      85   23 2020-01-10     87.5
1         HR    A      F      90   25 2020-02-15     87.5
2         IT    B      M      78   30 2021-03-20     81.5
3         IT    B      F      85   22 2021-04-10     81.5
4  Marketing    C      M      92   28 2020-05-30     90.0
5  Marketing    C      F      88   26 2020-06-25     90.0
6      Sales    D      M      75   21 2021-07-15     77.5
7      Sales    D      F      80   27 2021-08-01     77.5

In [108]:
df.groupby("Department").filter(lambda x:x["Salary"].mean()>85)

  Department Team Gender  Salary  Age   JoinDate  deptAvg
0         HR    A      M      85   23 2020-01-10     87.5
1         HR    A      F      90   25 2020-02-15     87.5
4  Marketing    C      M      92   28 2020-05-30     90.0
5  Marketing    C      F      88   26 2020-06-25     90.0

In [109]:
#merging and joinging

In [110]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [111]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [112]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing